POST http://localhost:4000/app/signup
Content-Type: application/json

{
    "firstName": "Paige",
    "lastName": "Reese",
    "username": "peony",
    "email": "paige.reese@mail.com",
    "password": "wanderer"
}